apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vtdu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qkkz-tenant/rhtap-demo-app/hacbs-test-project-vtdu@sha256:80c579731d8f340bafd9b8f32e1d1f6d6199d903e7d84530d66d14c69c64c4d3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
